version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_USER=quarkus
      - POSTGRES_DB=quarkus
